### ISSUE TITLE
httpclient is static or using IHttpClientFactory

### ISSUE THREAD

**Issue by liningit** [SteeltoeOSS/Common#8]
https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client
HttpClient is intended to be instantiated once and reused throughout the life of an application. The following conditions can result in SocketException errors:
Creating a new HttpClient instance per request.
Server under heavy load.

**Comment by TimHess** [comment]
Sorry, was there something you wanted to have addressed with this issue?

**Comment by TimHess** [comment]
I'm not clear what the intent was behind the creation of this issue - if you can elaborate, please feel free to re-open

**Comment by liningit** [comment]
HttpClient Should static  can't Creating a new HttpClient instance per request.

see
https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client
